// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdt_9sPtjjbCshGwwGYkClxXF3q4pDED0',
    appId: '1:496574485799:web:fd544bea4e79fb7a23c502',
    messagingSenderId: '496574485799',
    projectId: 'citi-guide-6a2b1',
    authDomain: 'citi-guide-6a2b1.firebaseapp.com',
    databaseURL: 'https://citi-guide-6a2b1-default-rtdb.firebaseio.com',
    storageBucket: 'citi-guide-6a2b1.firebasestorage.app',
    measurementId: 'G-PS36REXQH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQjT8cxKAnV6c703zzJ29PELxAVZKpaiQ',
    appId: '1:496574485799:android:ce81e91afdf7cec623c502',
    messagingSenderId: '496574485799',
    projectId: 'citi-guide-6a2b1',
    databaseURL: 'https://citi-guide-6a2b1-default-rtdb.firebaseio.com',
    storageBucket: 'citi-guide-6a2b1.firebasestorage.app',
  );
}
